### ISSUE TITLE
Greens showing up wrongly as rebels

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1161]
Scott Ludlam appears wrongly as a rebel [in this division](https://theyvoteforyou.org.au/divisions/senate/2017-02-15/3).

We say he voted 'Yes' when he actually voted 'No' [with the rest of his party](http://parlinfo.aph.gov.au/parlInfo/genpdf/chamber/hansards/5bf236bf-234f-412d-900f-b6f5448207dc/0075/hansard_frag.pdf;fileType=application%2Fpdf).

Peter Whish-Wilson appears wrongly as a rebel [in this division](https://theyvoteforyou.org.au/divisions/senate/2017-03-20/1).

We say he voted "Yes against the majority of the Australian Greens" when he actually voted Yes [alongside the rest of his party](http://parlinfo.aph.gov.au/parlInfo/genpdf/chamber/hansards/276adda7-0801-4128-8471-554c56960766/0044/hansard_frag.pdf;fileType=application%2Fpdf). This division is the bigger problem as the error creates a wrong result - the Yes voters actually won (we say they lost). We also list the division as occurring at 11.49 when it happened at 11.59 - I compared our 'preceding debate' on [OAF.org](http://www.openaustralia.org.au/senate/?id=2017-03-20.24.1) with [Hansard](http://www.aph.gov.au/Parliamentary_Business/Hansard/Hansard_Display?bid=chamber/hansards/276adda7-0801-4128-8471-554c56960766/&sid=0000) and both agree TVFY should say 11.59.

Is there any way to redo these TVFY divisions to correct the data? I assume something went wrong when it was originally pulled from the Parliament data?

These are the only two problem divisions I've found so far (I was looking at a rebellious One Nation Senator today and saw the two so-called Greens rebels - seemed most unusual so I investigated...) Will keep an eye out for more.

**Comment by henare** [comment]
I just noticed this too. My guess is that the feed we originally got from APH was wrong. They often make mistakes and these are later corrected.

The fix is for us to reparse and reload the data from the source for this day.

**Comment by equivalentideas** [comment]
@henare do you feel up for picking this one up too?

**Comment by henare** [comment]
@equivalentideas not right now. I think it would be good to do this in a big clear out of [hansard](https://github.com/openaustralia/publicwhip/issues?q=is%3Aissue+is%3Aopen+label%3A%22hansard+errors%22) parsing [issues](https://github.com/openaustralia/openaustralia/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aparser%20debates%20missing), maybe an audit of old Hansard, and maybe even parsing some older APH data as as been mentioned on https://github.com/openaustralia/openaustralia-parser/pull/17 (that would be particularly awesome).

**Comment by equivalentideas** [comment]
@henare sounds good to me 👍

**Comment by jamezpolley** [comment]
@MicaelaMicaela Could you look back over these issues and let me know if this is still a problem?

**Comment by MicaelaMicaela** [comment]
Sure @jamezpolley - will look at this today

**Comment by MicaelaMicaela** [comment]
The two divisions I mentioned above still have those same errors. Neither are related to #1190 since the affected senators haven't ever changed parties.

Today I've gone through all the cases we list of Greens who have rebelled (since, as a rule, Greens don't actually rebel) and I also found this error:

* [This division](https://theyvoteforyou.org.au/divisions/senate/2018-10-15/6) should be 8 Yes and 46 No (we have listed 48 No). Sen Jordon Steele-John wrongly listed as voting "No" against the rest of the Greens Party (he wasn't actually present that vote) and Sen Kim Carr of the Labor Party is listed as voting "No" despite not being there either.

There must be other errors, but I'm not sure how to find them except by being vigilant and coming across them by chance

**Comment by MicaelaMicaela** [comment]
Hi @jamezpolley, do you have any updates on this issue and #1190? Cheers :-)

**Comment by jamezpolley** [comment]
> Peter Whish-Wilson appears wrongly as a rebel [in this division](https://theyvoteforyou.org.au/divisions/senate/2017-03-20/1).
> 
> We say he voted "Yes against the majority of the Australian Greens" when he actually voted Yes [alongside the rest of his party](http://parlinfo.aph.gov.au/parlInfo/genpdf/chamber/hansards/276adda7-0801-4128-8471-554c56960766/0044/hansard_frag.pdf;fileType=application%2Fpdf). This division is the bigger problem as the error creates a wrong result - the Yes voters actually won (we say they lost). We also list the division as occurring at 11.49 when it happened at 11.59 - I compared our 'preceding debate' on [OAF.org](http://www.openaustralia.org.au/senate/?id=2017-03-20.24.1) with [Hansard](http://www.aph.gov.au/Parliamentary_Business/Hansard/Hansard_Display?bid=chamber/hansards/276adda7-0801-4128-8471-554c56960766/&sid=0000) and both agree TVFY should say 11.59.

Hansard shows both if you look at the [full text](https://www.aph.gov.au/Parliamentary_Business/Hansard/Hansard_Display?bid=chamber/hansards/276adda7-0801-4128-8471-554c56960766/&sid=0000) of the debate; but only the second division is correctly flagged as a division. The first division has its vote data there just in a simple table.

https://theyvoteforyou.org.au/divisions/senate/2017-03-20/1 is the 11:49 division, https://theyvoteforyou.org.au/divisions/senate/2017-03-20/2 is the 11:59 division.

So:
> "We also list the division as occurring at 11.49 when it happened at 11.59"
- actually there are two divisions and we're showing both, so that's okay. Hansard is only showing the second one - the first one is visible in the raw text of the speech but isn't showing properly as a division.

> We say he voted "Yes against the majority of the Australian Greens" when he actually voted Yes [alongside the rest of his party]

That's true for the 11:59 vote, and we show that. In the 11:49 vote, Hansard shows that he voted no, alongside the rest of the party. We've got that wrong. However, we're *less* wrong than hansard, who aren't correctly showing that first division at all.

There's nothing (easy) I can do here to fix this until Hansard is corrected. I did try parsing the XML that's currently posted, but it removes the first division from our site completely; so I'm leaving things as they are, on the grounds that it's more correct to show both divisions and have a few votes wrong on one of them, than to ignore the first division completely.

I've [tweeted](https://twitter.com/tchaypo/status/1101365020191944704) to ask about how the XML could be fixed.

**Comment by jamezpolley** [comment]
> Scott Ludlam appears wrongly as a rebel [in this division](https://theyvoteforyou.org.au/divisions/senate/2017-02-15/3).
> 
> We say he voted 'Yes' when he actually voted 'No' [with the rest of his party](http://parlinfo.aph.gov.au/parlInfo/genpdf/chamber/hansards/5bf236bf-234f-412d-900f-b6f5448207dc/0075/hansard_frag.pdf;fileType=application%2Fpdf).

This one is more straightforward; once again, two divisions, but this time, both are properly recorded in Hansard and we have a wrong vote in the second.

However: Hansard records a vote in this division from "Ludlum, S" instead of "Ludlam, S", so we can't simply pull in the upstream data here either.

Again, I've tweated at @aus_hansard asking for a fix. If we can't get that, we can fairly easily add a patch for this.
