### ISSUE TITLE
Delay between loading new divisions and division_info being populated

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/theyvoteforyou#1269]
## Backtrace

    line 14 of [PROJECT_ROOT]/app/models/division.rb: rescue in aye_majority
    line 14 of [PROJECT_ROOT]/app/models/division.rb: aye_majority
    line 74 of [PROJECT_ROOT]/app/models/division.rb: tied?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37542/faults/82182761)

**Comment by mlandauer** [comment]
Since this causes the site to error for a couple of minutes each day when new divisions are loaded we should get this fixed soon. I guess it's not going to be super crucial to address for the upcoming election because once the election starts and people might refer to TVFY for reference parliament will not actually be sitting and so this problem shouldn't occur.

**Comment by Taz17** [comment]
I thought about this, I came up with two ideas.

- Update `members cache` right after `application:load:members`, similarly update `divisions cache` right after `application:load:divisions` is executed. That reduces the time between `load` and `cache`.
This will require us update all the caches, excluding members and divisions since they have already been updated

- Update the cron job to run at an earlier time where the site receives less traffic.
