### ISSUE TITLE
Update documentation to explain what a 'strong' vote is (i.e. "Yes (strong)" and "No (strong)")

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1314]
A draft explanation:

> **What is a ‘strong’ vote?**
>
> When a division is added to a policy, we have to indicate how a supporter would vote. We do this by saying that a supporter would vote either: Yes (strong), Yes, No, or No (strong). We include a ‘strong’ option because some divisions are more significant than others. A division is considered ‘strong’ when two conditions are met:
>
> 1. the division is making a substantive (or real) change; and
>
> 2. the division is directly relevant to the policy (as opposed to only being partially or indirectly relevant).
>
> **What is a substantive (or real) change?**
>
> Many of the divisions in parliament are either procedural or symbolic. To be considered substantive, a vote must make a real change. Examples include a vote on an amendment that would change the wording of a bill, or a vote on whether to pass a bill and make it law.
>
> The only exceptions to this are the three solely procedural policies we have on TVFY, which are: (1) For letting all MPs to Senators speak in Parliament (procedural); (2) For speeding things along in Parliament (procedural); and (3) For suspending the rules to allow a vote to happen (procedural). For these three policies, all divisions are ranked as ‘strong’ despite only being procedural because the policies themselves are procedural in nature (that is, don’t make any real or substantive changes to our laws).

**Comment by mlandauer** [comment]
@katska could you please cast your wise eye over this wording. The intention is to explain how a vote is "strong" vs a "normal" vote. So, it should also be a beginning of a kind of editorial policy for how divisions and policies are written and edited. This is part of #1280

**Comment by katska** [comment]
@mlandauer I'm looking at this specific wording. Can you show me an example of where the wording currently appears?

**Comment by mlandauer** [comment]
@katska I don't actually know where this would appear. I guess that's one thing that needs working out ;-)

**Comment by katska** [comment]
Ok. So having thought a little bit about where this appears, I think this piece of work is 
- adding this explanation into https://theyvoteforyou.org.au/help/faq 
- check and add reference to voting categories throughout the FAQ

**Comment by katska** [comment]
Here's another version. See notes below afterwards.

What is a ‘strong’ vote?

Simply put a 'strong' vote is one that is more significant to a specific policy than other votes.

_Include Example_

When TheyVoteForYou adds a division to a policy, we have to show how a supporter would vote. We do this by showing that a supporter as voting either: Yes (strong), Yes, No, or No (strong). We include a ‘strong’ option for more significant divisions. 
We consider a division to be ‘strong’ when it's both significant and relevant to the policy.

What is a significant change?

Many of the divisions in parliament are either procedural or symbolic. For TheyVoteForYou to consider a vote significant, it must make a substantive (or real) change. Examples include a vote on an amendment that would change the wording of a bill, or a vote on whether to pass a bill and make it law.

_Include Example_

There are three specific exceptions. TheyVoteForYou lists 3 solely procedural policies which are: (1) For letting all MPs to Senators speak in Parliament (procedural); (2) For speeding things along in Parliament (procedural); and (3) For suspending the rules to allow a vote to happen (procedural). For these three policies, all divisions are ranked as ‘strong’ despite being procedural because the policies themselves are about the procedures in Parliament. (that is, don’t make any real or substantive changes to our laws).

Ok @tseyiokorodudu  @Taz17 have a read of the Mackay's draft and then the update. I'm keen to hear what you think :)

My thinking is: After some deliberation, I see a few things going on here. @mackaymackay has written is a really good explanation already. 

Thoughts behind the changes I included as suggestions above are:
- say 'significant' all the way through rather than switching to 'substantive (or real)'. I found that wording a bit confusing.
- summarise what a strong vote is at the top, to get attention, and a quick overview.
- give TheyVoteForYou ownership of the actions, by using the name TheyVoteForYou, and using active language 
- remove acronym TVFY and instead use the full name
- isolate the point that 'Strong refers to the Division status, not the degree to which the voter agrees'.
- simplify language and shorten sentences where ever possible
- including labelled screenshot examples of both significant (or not) and relevant (or not) could help

*I don't know if replacing 'substantive' with 'significant' works? "Substantive" is a specific technical and political word, significant' is more familiar word, but more specific and less value laden than 'important' which I also considered. It depends if the goal is to reveal the mysteries of more Parliamentary insider language (which we are already doing) or present an easier read. I'm not sure where the slider sits from making clear to overly simplifying. 

I ran it through a [basic set of readability tests](https://www.webfx.com/tools/read-able/check.php
) and it comes up readable by American) 16-17 year olds. 

You may have other ideas?

**Comment by mlandauer** [comment]
During a conversation with @katska I realised we're adding a degree of indirection in naming something a "strong" vote and then having to define it when we're actually trying to be clear about the meaning of it. So, why not just name the votes according to what they are now. So, for example they could be:
* Formal votes that change our laws
* Formal votes that don't change our laws 

We have to think a little more about what we do for those weird exception policies that are all about the procedural votes. Could they all be "normal" votes rather than "strong" votes?

**Comment by katska** [comment]
When I read "Many of the divisions in parliament are either procedural or symbolic." I question, does this mean there are procedural votes, that are also known as symbolic votes - OR - that there are procedural votes AND symbolic votes. If the latter (we have talked about votes that are considered by some (eg. independents) to be purely symbolic, but by others (eg. major party members) to be their way to put their view).

**Comment by katska** [comment]
> We have to think a little more about what we do for those weird exception policies that are all about the procedural votes. Could they all be "normal" votes rather than "strong" votes?

I'd rather not use the word 'normal' anywhere. How about 'ordinary'.

**Comment by mackaymackay** [comment]
I understand we're trying to use plain English to ensure accessibility, but it seems that using words like 'strong', 'significant', 'normal' or 'ordinary' may be confusing matters.

From what I've seen while working on TVFY, there are only three kinds of divisions in parliament: procedural, symbolic and substantive.

Procedural votes are on parliamentary procedure and relate to standing orders and practice. Examples: gagging orders, motions to suspend standing orders, motions to put the question. These votes are only linked to four TVFY policies because those four policies are procedural in nature - they are about letting something take place in parliament, such as a particular vote or speech, or speeding another vote along. The four procedural policies on TVFY are:

-  For letting all MPs or Senators speak in Parliament (procedural)  
-  For speeding things along in Parliament (procedural) 
-  For suspending the rules to allow a vote to happen (procedural) 
-  For considering legislation to create a federal anti-corruption commission (procedural) 

Symbolic votes express a view on a subject but don't make actual legal changes. Examples: most second reading amendments and most general Senate motions. In line with recent changes to TVFY, symbolic votes are no longer ever ranked as 'strong.' They are only connected to policies as 'ordinary' votes no matter how directly relevant they are to the policy area.

Substantive votes actually have legal consequences. Examples: amending a bill, passing a bill, disallowing a regulation (i.e. stopping a regulation from having legal force). Substantive votes are ranked as 'strong' on TVFY if they are directly relevant to the policy in question. They are ranked as 'ordinary' if they are only indirectly related (i.e. related enough to connect to a policy, but not enough to merit the 'strong' moniker).

**Comment by katska** [comment]
@mackaymackay Thank you for that breakdown, it's very clear and specific, so that's very helpful. All of this information can be in the FAQ.
I do think we will still need a short description, which then people can follow to the longer explanation, as well as a way to see the difference between the two types of votes. Matthew's outline above is also about reorganising the way the votes are seen, so that the directly relevant (currently known as 'strong', or strongly weighted votes) would be presented first, with the first category labelling and then the second category shown separately, under the second heading, rather than all being jumbled up together. So it may be two boxes, or like a separate paragraph. Does that make sense to you?

Also I think we're all in agreement around the current wording not quite getting to the heart of what we're trying to convey. 
Could a short description be something like:
"votes that affect our laws that are directly relevant to this policy" 
while "symbolic, or procedural, or other votes that affect laws that are somewhat connected to the policy".
