### ISSUE TITLE
Consider 'retiring' older policies

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/theyvoteforyou#1384]
MP Wilkie's team has written and raised concerns about older policies and divisions being included in the voting record. Note that this issue only affects long-serving representatives.

While selectively removing old divisions from policies is problematic (it could give rise to accusations that we are manipulating the voting data), it may be worthwhile to retire policies after a certain number of years have passed without any relevant divisions being attached.

**Comment by mlandauer** [comment]
I think as a matter of principle we shouldn't retire "old" policies. I do think we should instead consider alternative ways that people can look at individual's voting records. For instance it would seem reasonable to me that we could add an option on a policy page for instance such as https://theyvoteforyou.org.au/policies/3 to only show votes that happened in a particular date range (or a sitting of parliament perhaps). We could do this on several of the other pages.

I do think the default of showing the whole history is a reasonable one considering we are focusing on the voting record of **people** rather than the voting records of people in particular parties or parliaments. Having said that there are perfectly legitimate reasons why you would be interested in looking at these alternatives. They just shouldn't necessarily be the defaults.
