### ISSUE TITLE
Incorrect voting data 

### ISSUE THREAD

**Issue by Lemmon-cloud** [openaustralia/theyvoteforyou#1489]
Andrew Hastie publicly abstained from voting yes in the 2016 same sex marriage plebiscite

**Comment by mackaymackay** [comment]
Thank you for posting this issue - it is always helpful when people flag potential errors in our data so we can address them. 

However, in this case, there does not appear to be an error. I checked the official [House of Representatives Hansard](https://parlinfo.aph.gov.au/parlInfo/download/chamber/hansardr/49c9d51c-41fd-4c99-9918-985afdc5fb8e/toc_pdf/House%20of%20Representatives_2016_10_20_4488_Official_DISTRIBUTED.pdf;fileType=application%2Fpdf#search=%22chamber/hansardr/49c9d51c-41fd-4c99-9918-985afdc5fb8e/0000%22) and it shows Mr Hastie voting Yes to giving the [Plebiscite (Same-Sex Marriage) Bill 2016](https://theyvoteforyou.org.au/divisions/representatives/2016-10-20/5) a second and third reading, which is why he is showing up as a supporter of our policy for [a same-sex marriage plebiscite](https://theyvoteforyou.org.au/policies/129).
